### ISSUE TITLE
Potential problems with the filters of the study metadata table of the ‘Summary Tables’ section 

### ISSUE THREAD

**Issue by pydemull** [RoryChenXY/DataRepExp_public#1]
In ‘Summary Tables’ section of the app, first table, the list of the countries is not complete. I guess the items are the countries corresponding to the fake studies used in the app. Thus, is this a problem for future projects with studies that would be conducted in countries that are no available in the list ? Would not be better to do as for the ‘Study’ filter where people should just write the searched name ? Or should you provide a full list of the existing countries? Maybe I have missed something?

**Comment by pydemull** [comment]
You can forget my second remark regarding the 'Continent' filter, I have made a trial while a filter was applied, sorry.

**Comment by RoryChenXY** [comment]
Dear Pydemull,

The summary table is corresponding to the fake studies used in the app.

The filter tab dropdown option is generated from the data provided. 

For example: 
`
    shiny::checkboxGroupInput(
      inputId = NS(id,"country"),
      label = "Country",
      choices = levels(df$COUNTRY),
      selected = levels(df$COUNTRY)
    )
`
I hope this answers your question.

Best,
Rory

**Comment by pydemull** [comment]
Thanks Rory, I also had the following remarks regarding the Summary table section (which has been changed with the golem branch if I'm not wrong):
3.	In ‘Summary Tables’ section of the app, second table, ‘Administration’ and ‘Demographics’ filters are not available. Is this normal?
4.	In ‘Summary Tables’ section of the app, the numeric filters with slide bars are not easy to used since we cannot always see the bounds of the filters we are using. Would it be possible to improve it?

Not sure that these old remarks are still appropriate. Can you confirm this?

**Comment by pydemull** [comment]
Sorry my remark about the golem version is not correct. I made this remark because I looked at the online app, that is not exactly the same as the app I had when I open it (the golem version) on my machine. I suggest to pay attention to the update of the online app so that it corresponds to the code shown on GitHub. In this way, it could be good to add a version number of the app in the app itself so that the user can know with which version of the app he/she is currently working.

**Comment by RoryChenXY** [comment]
_3. In the ‘Summary Tables’ section of the app, the second table, ‘Administration’ and ‘Demographics’ filters are not available.
Is this normal?_ 
- For this one, it is because all studies have  ‘Administration’ and ‘Demographics’ data (usually) so all values are 'Yes', and DT disabled the filters automatically.

_4. In ‘Summary Tables’ section of the app, the numeric filters with slide bars are not easy to used since we cannot always see the bounds of the filters we are using. Would it be possible to improve it?_
-  the filters are DT default options, I didn't find additional styling options: https://rstudio.github.io/DT/008-filter.html
-  Custom filtering - range search (may require user-defined JS function, need to learn more): https://datatables.net/examples/plug-ins/range_filtering.html
-  I can add slider input filters on top like the filter tab on top
-  My concern is duplicate filter functions - I don't know how to disable the current filters on selected numeric columns of DT tables. 
-  I will look more into this, Thanks!

**Comment by RoryChenXY** [comment]
@pydemull, thank you for your input, I have made some updates:
1. the current online version reflects the updated version
2. added version number on the first tab
3. update ‘Summary Tables’ section of the app, the numeric filters with slide bars to vertical, it is not perfect but is an improvement

**Comment by RoryChenXY** [comment]
I think all issues here are resolved

**Comment by pydemull** [comment]
Thanks Rory, that's ok. Indeed the slide bar for the numeric filter  could be better if placed horizontally but it works fine.
