### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by pydemull** [RoryChenXY/DataRepExp_public#6]
1.	In the section “Overview/Data Visualisation Tool for Data Repositories”, there is a problem with ‘Chen et al. [citation]’. The citation is missing.
2. 	In the file https://github.com/RoryChenXY/DataRepExp_public/blob/main/dataprep/dataprep.R; you load several packages twice because you load the tidyverse collection and also you load single packages that are components of the tidyverse collection: dplyr, tidyr, forcats, magrittr.  This is not very efficient and could be updated (eg, by loading only the required packages and not all the collection of tidyverse packages. Because magrittr is a dependency imported in the environment when loading dplyr, it might not be necessary to explicitly load it.
3.	Typo in the README: “Deatail Notes”. (Deployment Notes, bullet 1).
4.	In the Data Preparation section (https://github.com/RoryChenXY/DataRepExp_public/blob/golem/notes/1_dataprep.md) , it would be nice to explain that at the end, the user should have an RData file containing a list of the data frames required so that the app works, correct?
5.	About a comment in the Documentation: Not R skill only is required to modify the app but also an intermediate level in Shiny.
6.	It would be nice that the csv files exported have a name that describe more specifically their content.
7.	In the visualization tab (Metadata), graphics are nice. Would it possible to make sure that metadata that appear on the bar plots can all be viewed in the box when we have the cursor on the graphic.
8.	The README file should be updated so that it exactly corresponds to the content of the app (cf. screenshots). This remarks concern at least the online app.
9. It would be nice to have some documentation to explain how to install the app locally (eg with RStudio).

**Comment by RoryChenXY** [comment]
@pydemull, thank you for your input. I  have address the following:
1. problem with ‘Chen et al. [citation]’: this is for the current paper that doesn't have a DOI yet, will update the contents once the paper is published.
6. csv file exported now have corresponding names
7. tooltip updated - add line breaker so all information can be viewed

Still working on the documentation. Thanks.

**Comment by RoryChenXY** [comment]
1. In the section “Overview/Data Visualisation Tool for Data Repositories”, there is a problem with ‘Chen et al. [citation]’. The citation is missing. **- Waiting for the current paper DOI**
2.  In the file https://github.com/RoryChenXY/DataRepExp_public/blob/main/dataprep/dataprep.R; you load several packages twice because you load the tidyverse collection and also you load single packages that are components of the tidyverse collection: dplyr, tidyr, forcats, magrittr. This is not very efficient and could be updated (eg, by loading only the required packages and not all the collection of tidyverse packages. Because magrittr is a dependency imported in the environment when loading dplyr, it might not be necessary to explicitly load it. **- updated, removed tidyverse **
3. Typo in the README: “Deatail Notes”. (Deployment Notes, bullet 1). **- updated**
4. In the Data Preparation section (https://github.com/RoryChenXY/DataRepExp_public/blob/golem/notes/1_dataprep.md) , it would be nice to explain that at the end, the user should have an RData file containing a list of the data frames required so that the app works, correct? **- made changes**
5. About a comment in the Documentation: Not R skill only is required to modify the app but also an intermediate level in Shiny. **- Agreed, I think also modules and golem**
6.  It would be nice that the csv files exported have a name that describe more specifically their content.  **- updated**
7. In the visualization tab (Metadata), graphics are nice. Would it possible to make sure that metadata that appear on the bar plots can all be viewed in the box when we have the cursor on the graphic.  **- updated tooltip**
8. The README file should be updated so that it exactly corresponds to the content of the app (cf. screenshots). This remarks concern at least the online app.  **- updated screenshot**
9. It would be nice to have some documentation to explain how to install the app locally (eg with RStudio).  **- updated**

**Comment by pydemull** [comment]
Thanks Rory, it seems good to me!
